### ISSUE TITLE
想请求大大们的援助，在运行api.py时出现定义问题

### ISSUE THREAD

**Issue by blackcat203** [wordweb/langchain-ChatGLM-and-TigerBot#4]
系统win11
CPU:AMD1920X
GPU:RTX4070TI
在按照步骤做到".\Python310\python.exe api.py“后管理员命令提示符出现了下面问题
这个问题是我在前面安装模块的时候没有将模块加入PATH到环境？还是说需要我自己进入api.py进行手动定义?
我只有看过一点编程的课程，也是第一次使用github，现在碰到这个问题后询问gpt也得不到答案，恳请作者大大指点一二。如果可以的话能把我拉进项目项目交流群吗？我的联系方式394244522，麻烦大大了
```
C:\langchain-ChatGLM-and-TigerBot>.\Python310\python.exe api.py
INFO  2023-09-23 16:13:55,812-1d:
loading model config
llm device: cuda
embedding device: cuda
dir: C:\langchain-ChatGLM-and-TigerBot
flagging username: a4556e66ca804901b9d038a8cd4c3f44

Loading model/TigerBot...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.12s/it]
Loaded the model in 211.68 seconds.
Traceback (most recent call last):
  File "C:\langchain-ChatGLM-and-TigerBot\api.py", line 407, in <module>
    api_start(args.host, args.port)
  File "C:\langchain-ChatGLM-and-TigerBot\api.py", line 361, in api_start
    llm_model_ins = shared.loaderLLM()
  File "C:\langchain-ChatGLM-and-TigerBot\models\shared.py", line 42, in loaderLLM
    provides_class = getattr(sys.modules['models'], llm_model_info['provides'])
AttributeError: module 'models' has no attribute 'TigerBotLLM'
```

**Comment by tangbiubiu** [comment]
在models/__init__.py中添加“from .tigerbot_llm import TigerBotLLM”。

**Comment by tangbiubiu** [comment]
在`models/__init__.py`中添加“from .tigerbot_llm import TigerBotLLM”。

**Comment by tangbiubiu** [comment]
在`models/__init__.py`中添加一行：`from .tigerbot_llm import TigerBotLLM`。
